/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nqueens;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JLabel;

/**
 *
 * @author Ikhlas ^_^
 */
public class board extends javax.swing.JFrame {

    static int selN = 4;
    static int[] solution = null;
    
    /**
     * Creates new form board
     */
    public board() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        barregauche = new javax.swing.JPanel();
        Title = new java.awt.Label();
        Solve = new javax.swing.JButton();
        GA = new javax.swing.JLabel();
        N_val = new javax.swing.JLabel();
        Nval = new javax.swing.JComboBox<>();
        Reset = new javax.swing.JButton();
        carreau1 = new javax.swing.JPanel();
        Q1 = new javax.swing.JLabel();
        alt1 = new javax.swing.JLabel();
        carreau2 = new javax.swing.JPanel();
        Q2 = new javax.swing.JLabel();
        alt2 = new javax.swing.JLabel();
        carreau3 = new javax.swing.JPanel();
        Q3 = new javax.swing.JLabel();
        alt3 = new javax.swing.JLabel();
        carreau4 = new javax.swing.JPanel();
        Q4 = new javax.swing.JLabel();
        alt4 = new javax.swing.JLabel();
        carreau5 = new javax.swing.JPanel();
        Q5 = new javax.swing.JLabel();
        alt5 = new javax.swing.JLabel();
        carreau6 = new javax.swing.JPanel();
        Q6 = new javax.swing.JLabel();
        alt6 = new javax.swing.JLabel();
        carreau7 = new javax.swing.JPanel();
        Q7 = new javax.swing.JLabel();
        alt7 = new javax.swing.JLabel();
        carreau8 = new javax.swing.JPanel();
        Q8 = new javax.swing.JLabel();
        alt8 = new javax.swing.JLabel();
        carreau9 = new javax.swing.JPanel();
        Q9 = new javax.swing.JLabel();
        alt9 = new javax.swing.JLabel();
        carreau10 = new javax.swing.JPanel();
        Q10 = new javax.swing.JLabel();
        alt10 = new javax.swing.JLabel();
        carreau11 = new javax.swing.JPanel();
        Q11 = new javax.swing.JLabel();
        alt11 = new javax.swing.JLabel();
        carreau12 = new javax.swing.JPanel();
        Q12 = new javax.swing.JLabel();
        alt12 = new javax.swing.JLabel();
        carreau13 = new javax.swing.JPanel();
        Q13 = new javax.swing.JLabel();
        alt13 = new javax.swing.JLabel();
        carreau14 = new javax.swing.JPanel();
        Q14 = new javax.swing.JLabel();
        alt14 = new javax.swing.JLabel();
        carreau15 = new javax.swing.JPanel();
        Q15 = new javax.swing.JLabel();
        alt15 = new javax.swing.JLabel();
        carreau16 = new javax.swing.JPanel();
        Q16 = new javax.swing.JLabel();
        alt16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("N-Queens");
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(300, 200));
        setPreferredSize(new java.awt.Dimension(800, 595));

        barregauche.setBackground(new java.awt.Color(102, 102, 102));
        barregauche.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setName(""); // NOI18N
        Title.setText("   N-Queens");

        Solve.setBackground(new java.awt.Color(102, 102, 102));
        Solve.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Solve.setForeground(new java.awt.Color(255, 255, 255));
        Solve.setText("Solve");
        Solve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Solve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolveMouseClicked(evt);
            }
        });

        GA.setBackground(new java.awt.Color(102, 102, 102));
        GA.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        GA.setForeground(new java.awt.Color(255, 255, 255));
        GA.setText("  Genetic Algorithm");

        N_val.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        N_val.setForeground(new java.awt.Color(255, 255, 255));
        N_val.setText("N = ");

        Nval.setBackground(new java.awt.Color(102, 102, 102));
        Nval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nval.setForeground(new java.awt.Color(255, 255, 255));
        Nval.setMaximumRowCount(1);
        Nval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "8" }));
        Nval.setName("Nval"); // NOI18N
        Nval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NvalActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(102, 102, 102));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Rest Board");
        Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barregaucheLayout = new javax.swing.GroupLayout(barregauche);
        barregauche.setLayout(barregaucheLayout);
        barregaucheLayout.setHorizontalGroup(
            barregaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barregaucheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GA, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(barregaucheLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(barregaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(Solve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(barregaucheLayout.createSequentialGroup()
                        .addComponent(N_val)
                        .addGap(18, 18, 18)
                        .addComponent(Nval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barregaucheLayout.setVerticalGroup(
            barregaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barregaucheLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(GA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(barregaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N_val, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(Solve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        carreau1.setBackground(new java.awt.Color(0, 0, 0));
        carreau1.setMaximumSize(new java.awt.Dimension(131, 131));
        carreau1.setMinimumSize(new java.awt.Dimension(131, 131));

        Q1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N
        Q1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                Q1ComponentHidden(evt);
            }
        });

        alt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape (1).png"))); // NOI18N
        alt1.setToolTipText("");

        javax.swing.GroupLayout carreau1Layout = new javax.swing.GroupLayout(carreau1);
        carreau1.setLayout(carreau1Layout);
        carreau1Layout.setHorizontalGroup(
            carreau1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        carreau1Layout.setVerticalGroup(
            carreau1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau1Layout.createSequentialGroup()
                .addGroup(carreau1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carreau1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Q1))
                    .addGroup(carreau1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(alt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        carreau2.setBackground(new java.awt.Color(204, 204, 204));

        Q2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape2 (1).png"))); // NOI18N
        alt2.setToolTipText("");

        javax.swing.GroupLayout carreau2Layout = new javax.swing.GroupLayout(carreau2);
        carreau2.setLayout(carreau2Layout);
        carreau2Layout.setHorizontalGroup(
            carreau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Q2)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(carreau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carreau2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(alt2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        carreau2Layout.setVerticalGroup(
            carreau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(carreau2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carreau2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(alt2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        carreau3.setBackground(new java.awt.Color(0, 0, 0));

        Q3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape (1).png"))); // NOI18N
        alt3.setToolTipText("");

        javax.swing.GroupLayout carreau3Layout = new javax.swing.GroupLayout(carreau3);
        carreau3.setLayout(carreau3Layout);
        carreau3Layout.setHorizontalGroup(
            carreau3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Q3)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(carreau3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carreau3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(alt3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        carreau3Layout.setVerticalGroup(
            carreau3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(carreau3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carreau3Layout.createSequentialGroup()
                    .addComponent(alt3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        carreau4.setBackground(new java.awt.Color(204, 204, 204));

        Q4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape2 (1).png"))); // NOI18N
        alt4.setToolTipText("");

        javax.swing.GroupLayout carreau4Layout = new javax.swing.GroupLayout(carreau4);
        carreau4.setLayout(carreau4Layout);
        carreau4Layout.setHorizontalGroup(
            carreau4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau4Layout.createSequentialGroup()
                .addGroup(carreau4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carreau4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Q4))
                    .addGroup(carreau4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(alt4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        carreau4Layout.setVerticalGroup(
            carreau4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        carreau5.setBackground(new java.awt.Color(204, 204, 204));

        Q5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape2 (1).png"))); // NOI18N
        alt5.setToolTipText("");

        javax.swing.GroupLayout carreau5Layout = new javax.swing.GroupLayout(carreau5);
        carreau5.setLayout(carreau5Layout);
        carreau5Layout.setHorizontalGroup(
            carreau5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(carreau5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau5Layout.setVerticalGroup(
            carreau5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(carreau5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        carreau6.setBackground(new java.awt.Color(0, 0, 0));

        Q6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape (1).png"))); // NOI18N
        alt6.setToolTipText("");

        javax.swing.GroupLayout carreau6Layout = new javax.swing.GroupLayout(carreau6);
        carreau6.setLayout(carreau6Layout);
        carreau6Layout.setHorizontalGroup(
            carreau6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Q6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(carreau6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau6Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau6Layout.setVerticalGroup(
            carreau6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Q6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(carreau6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        carreau7.setBackground(new java.awt.Color(204, 204, 204));

        Q7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape2 (1).png"))); // NOI18N
        alt7.setToolTipText("");

        javax.swing.GroupLayout carreau7Layout = new javax.swing.GroupLayout(carreau7);
        carreau7.setLayout(carreau7Layout);
        carreau7Layout.setHorizontalGroup(
            carreau7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau7Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Q7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(carreau7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau7Layout.setVerticalGroup(
            carreau7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Q7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(carreau7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alt7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        carreau8.setBackground(new java.awt.Color(0, 0, 0));

        Q8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape (1).png"))); // NOI18N
        alt8.setToolTipText("");

        javax.swing.GroupLayout carreau8Layout = new javax.swing.GroupLayout(carreau8);
        carreau8.setLayout(carreau8Layout);
        carreau8Layout.setHorizontalGroup(
            carreau8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau8Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Q8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(carreau8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carreau8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(alt8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        carreau8Layout.setVerticalGroup(
            carreau8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Q8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(carreau8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alt8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        carreau9.setBackground(new java.awt.Color(0, 0, 0));

        Q9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape (1).png"))); // NOI18N
        alt9.setToolTipText("");

        javax.swing.GroupLayout carreau9Layout = new javax.swing.GroupLayout(carreau9);
        carreau9.setLayout(carreau9Layout);
        carreau9Layout.setHorizontalGroup(
            carreau9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau9Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Q9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(carreau9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carreau9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(alt9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        carreau9Layout.setVerticalGroup(
            carreau9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Q9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(carreau9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau9Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        carreau10.setBackground(new java.awt.Color(204, 204, 204));

        Q10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape2 (1).png"))); // NOI18N
        alt10.setToolTipText("");

        javax.swing.GroupLayout carreau10Layout = new javax.swing.GroupLayout(carreau10);
        carreau10.setLayout(carreau10Layout);
        carreau10Layout.setHorizontalGroup(
            carreau10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau10Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Q10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(carreau10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carreau10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(alt10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        carreau10Layout.setVerticalGroup(
            carreau10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Q10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(carreau10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau10Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        carreau11.setBackground(new java.awt.Color(0, 0, 0));

        Q11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape (1).png"))); // NOI18N
        alt11.setToolTipText("");

        javax.swing.GroupLayout carreau11Layout = new javax.swing.GroupLayout(carreau11);
        carreau11.setLayout(carreau11Layout);
        carreau11Layout.setHorizontalGroup(
            carreau11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau11Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Q11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(carreau11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau11Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau11Layout.setVerticalGroup(
            carreau11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Q11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(carreau11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alt11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        carreau12.setBackground(new java.awt.Color(204, 204, 204));

        Q12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape2 (1).png"))); // NOI18N
        alt12.setToolTipText("");

        javax.swing.GroupLayout carreau12Layout = new javax.swing.GroupLayout(carreau12);
        carreau12.setLayout(carreau12Layout);
        carreau12Layout.setHorizontalGroup(
            carreau12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Q12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(carreau12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau12Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau12Layout.setVerticalGroup(
            carreau12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau12Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Q12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(carreau12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau12Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        carreau13.setBackground(new java.awt.Color(204, 204, 204));

        Q13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape2 (1).png"))); // NOI18N
        alt13.setToolTipText("");

        javax.swing.GroupLayout carreau13Layout = new javax.swing.GroupLayout(carreau13);
        carreau13.setLayout(carreau13Layout);
        carreau13Layout.setHorizontalGroup(
            carreau13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau13Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Q13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(carreau13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau13Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau13Layout.setVerticalGroup(
            carreau13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Q13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(carreau13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carreau13Layout.createSequentialGroup()
                    .addComponent(alt13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        carreau14.setBackground(new java.awt.Color(0, 0, 0));

        Q14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape (1).png"))); // NOI18N
        alt14.setToolTipText("");

        javax.swing.GroupLayout carreau14Layout = new javax.swing.GroupLayout(carreau14);
        carreau14.setLayout(carreau14Layout);
        carreau14Layout.setHorizontalGroup(
            carreau14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau14Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(Q14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(carreau14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau14Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau14Layout.setVerticalGroup(
            carreau14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau14Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Q14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(carreau14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau14Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        carreau15.setBackground(new java.awt.Color(204, 204, 204));

        Q15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape2 (1).png"))); // NOI18N
        alt15.setToolTipText("");

        javax.swing.GroupLayout carreau15Layout = new javax.swing.GroupLayout(carreau15);
        carreau15.setLayout(carreau15Layout);
        carreau15Layout.setHorizontalGroup(
            carreau15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau15Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(Q15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(carreau15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau15Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt15, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau15Layout.setVerticalGroup(
            carreau15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau15Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Q15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(carreau15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alt15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        carreau16.setBackground(new java.awt.Color(0, 0, 0));

        Q16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/chess-piece-queen-king-clip-art-chess-69c1f6e5c100e51da0603d328fc26610 (1).png"))); // NOI18N

        alt16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nqueens/shape (1).png"))); // NOI18N
        alt16.setToolTipText("");

        javax.swing.GroupLayout carreau16Layout = new javax.swing.GroupLayout(carreau16);
        carreau16.setLayout(carreau16Layout);
        carreau16Layout.setHorizontalGroup(
            carreau16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau16Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Q16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(carreau16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreau16Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alt16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        carreau16Layout.setVerticalGroup(
            carreau16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreau16Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Q16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(carreau16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alt16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barregauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carreau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carreau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carreau3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carreau4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(carreau5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carreau6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carreau7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carreau8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(carreau9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(carreau10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(carreau11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(carreau12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(carreau13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(carreau14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(carreau15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(carreau16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barregauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(carreau3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreau4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carreau2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carreau1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carreau6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreau5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreau7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreau8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carreau12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreau11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreau10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreau9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carreau13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carreau15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carreau16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carreau14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        carreau1.getAccessibleContext().setAccessibleName("");

        pack();
    }

    
    private void NvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NvalActionPerformed
        // TODO add your handling code here:
        String selectedN = Nval.getSelectedItem().toString();
        selN = Integer.parseInt(selectedN);
        
    }

    private void SolveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolveMouseClicked
       
        Methods method = new Methods();
        solution=method.method1(selN);
        for (int i = 0; i < selN; i++)
        {
            if (i == 0)
            {
                if(solution[i] == 0)
                {
                    Q1.setVisible(true);
                    Q5.setVisible(false);
                    Q9.setVisible(false);
                    Q13.setVisible(false);
                }
                if(solution[i] == 1)
                {
                    Q1.setVisible(false);
                    Q5.setVisible(true);
                    Q9.setVisible(false);
                    Q13.setVisible(false);
                }
                if(solution[i] == 2)
                {
                    Q1.setVisible(false);
                    Q5.setVisible(false);
                    Q9.setVisible(true);
                    Q13.setVisible(false);
                }
                if(solution[i] == 3)
                {
                    Q1.setVisible(false);
                    Q5.setVisible(false);
                    Q9.setVisible(false);
                    Q13.setVisible(true);
                }
            }
            else if (i == 1)
            {
                if(solution[i] == 0)
                {
                    Q2.setVisible(true);
                    Q6.setVisible(false);
                    Q10.setVisible(false);
                    Q14.setVisible(false);
                }
                if(solution[i] == 1)
                {
                    Q2.setVisible(false);
                    Q6.setVisible(true);
                    Q10.setVisible(false);
                    Q14.setVisible(false);
                }
                if(solution[i] == 2)
                {
                    Q2.setVisible(false);
                    Q6.setVisible(false);
                    Q10.setVisible(true);
                    Q14.setVisible(false);
                }
                if(solution[i] == 3)
                {
                    Q2.setVisible(false);
                    Q6.setVisible(false);
                    Q10.setVisible(false);
                    Q14.setVisible(true);
                }
            }
            else if (i == 2)
            {
                if(solution[i] == 0)
                {
                    Q3.setVisible(true);
                    Q7.setVisible(false);
                    Q11.setVisible(false);
                    Q15.setVisible(false);
                }
                if(solution[i] == 1)
                {
                    Q3.setVisible(false);
                    Q7.setVisible(true);
                    Q11.setVisible(false);
                    Q15.setVisible(false);
                }
                if(solution[i] == 2)
                {
                    Q3.setVisible(false);
                    Q7.setVisible(false);
                    Q11.setVisible(true);
                    Q15.setVisible(false);
                }
                if(solution[i] == 3)
                {
                    Q3.setVisible(false);
                    Q7.setVisible(false);
                    Q11.setVisible(false);
                    Q15.setVisible(true);
                }
            }
            else
            {
                if(solution[i] == 0)
                {
                    Q4.setVisible(true);
                    Q8.setVisible(false);
                    Q12.setVisible(false);
                    Q16.setVisible(false);
                }
                if(solution[i] == 1)
                {
                    Q4.setVisible(false);
                    Q8.setVisible(true);
                    Q12.setVisible(false);
                    Q16.setVisible(false);
                }
                if(solution[i] == 2)
                {
                    Q4.setVisible(false);
                    Q8.setVisible(false);
                    Q12.setVisible(true);
                    Q16.setVisible(false);
                }
                if(solution[i] == 3)
                {
                    Q4.setVisible(false);
                    Q8.setVisible(false);
                    Q12.setVisible(false);
                    Q16.setVisible(true);
                }
            }
        }
        
        System.out.println("N ="+ selN);
        
        
    }

    
    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        
        Q1.setVisible(false);
        Q2.setVisible(false);
        Q3.setVisible(false);
        Q4.setVisible(false);
        Q5.setVisible(false);
        Q6.setVisible(false);
        Q7.setVisible(false);
        Q8.setVisible(false);
        Q9.setVisible(false);
        Q10.setVisible(false);
        Q11.setVisible(false);
        Q12.setVisible(false);
        Q13.setVisible(false);
        Q14.setVisible(false);
        Q15.setVisible(false);
        Q16.setVisible(false);
       
    }

    private void Q1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Q1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_Q1ComponentHidden

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
    	//int n=8;
    	
    	if(solution!= null) {
    		for (int i = 0; i < solution.length; i++)  {
    			
    			System.out.println("Solution found for i : \n" + solution[i]);
    			
    		}
    	System.out.println("Solution found : " + Methods.arrayToString(solution));
    	
    	
        
    }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new board().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GA;
    private javax.swing.JLabel N_val;
    private javax.swing.JComboBox<String> Nval;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q10;
    private javax.swing.JLabel Q11;
    private javax.swing.JLabel Q12;
    private javax.swing.JLabel Q13;
    private javax.swing.JLabel Q14;
    private javax.swing.JLabel Q15;
    private javax.swing.JLabel Q16;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Q5;
    private javax.swing.JLabel Q6;
    private javax.swing.JLabel Q7;
    private javax.swing.JLabel Q8;
    private javax.swing.JLabel Q9;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Solve;
    private java.awt.Label Title;
    private javax.swing.JLabel alt1;
    private javax.swing.JLabel alt10;
    private javax.swing.JLabel alt11;
    private javax.swing.JLabel alt12;
    private javax.swing.JLabel alt13;
    private javax.swing.JLabel alt14;
    private javax.swing.JLabel alt15;
    private javax.swing.JLabel alt16;
    private javax.swing.JLabel alt2;
    private javax.swing.JLabel alt3;
    private javax.swing.JLabel alt4;
    private javax.swing.JLabel alt5;
    private javax.swing.JLabel alt6;
    private javax.swing.JLabel alt7;
    private javax.swing.JLabel alt8;
    private javax.swing.JLabel alt9;
    private javax.swing.JPanel barregauche;
    private javax.swing.JPanel carreau1;
    private javax.swing.JPanel carreau10;
    private javax.swing.JPanel carreau11;
    private javax.swing.JPanel carreau12;
    private javax.swing.JPanel carreau13;
    private javax.swing.JPanel carreau14;
    private javax.swing.JPanel carreau15;
    private javax.swing.JPanel carreau16;
    private javax.swing.JPanel carreau2;
    private javax.swing.JPanel carreau3;
    private javax.swing.JPanel carreau4;
    private javax.swing.JPanel carreau5;
    private javax.swing.JPanel carreau6;
    private javax.swing.JPanel carreau7;
    private javax.swing.JPanel carreau8;
    private javax.swing.JPanel carreau9;
    // End of variables declaration//GEN-END:variables
}
